### ISSUE TITLE
Missing License - Please add

### ISSUE THREAD

**Issue by gschmottlach** [karlwestin/node-waveheader#3]
Would you please add a license to this repo. I'd like to be able to leverage this for a project I'm working on but without a license it's unclear how I can use it. If acceptable, I would prefer if it were a MIT license to make it consistent with other Node.js modules.

Thanks . . .

**Comment by karlwestin** [comment]
Hi! 
I've added the Apache 2.0 license. It's almost like the MIT, github gives you a quick overview on the top of the license page https://github.com/karlwestin/node-waveheader/blob/master/LICENSE.md
